### ISSUE TITLE
Support for gprc 1.40

### ISSUE THREAD

**Issue by gromlin2** [eWaterCycle/setup-grpc#1]
Hey everyone,

I'd love to use this action with grpc 1.40.
I ran the steps described in the Readme for that verision in my fork, but I think the workflow itself can't run in a fork (the changes in the created PR seem off).

Any chance support for 1.40 can be added or the permission to run workflows on this repo granted?

Thanks

David

**Comment by sverhoeven** [comment]
Versions 147.3, 1.48.2, 1.5.1 have been added.
